### ISSUE TITLE
Crash on x86_64

### ISSUE THREAD

**Issue by M1cha** [MerlijnWajer/tracy#43] opened 2014-09-24 12:52 UTC
I just compiled tracy and ran any test. but it crashes at the beginning.

Kernel: Linux m1cha-NB 3.13.0-35-generic #62-Ubuntu SMP Fri Aug 15 01:58:42 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
OS: Ubuntu 14.04.1 LTS
GCC: Ubuntu 4.8.2-19ubuntu1

crash:
```
--------------------------------------------------------------------------------
Whoops: No such process
Function: tracy_wait_event, File: tracy-event.c, Line: 501
Arguments: PTRACE_GETSIGINFO, pid (0), ((void *)0), &siginfo
--------------------------------------------------------------------------------
tests/fork(tracy_backtrace+0x1f)[0x40334d]
tests/fork(tracy_wait_event+0x91f)[0x40708a]
tests/fork(tracy_main+0x40)[0x40352b]
tests/fork(main+0x76)[0x401e03]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f11f31e2ec5]
tests/fork[0x401cc9]
[0x0]
[0x0]
tests/fork(_start+0x0)[0x401ca0]
[0x7fffdb42ccf0]
tracy_main: tracy_wait_Event returned NULL
```

**Comment by mariotti** [comment] 2015-01-01 23:32
base, bash, inject-simple, fuzz-write tests where working on my machine:

[mariotti@localhost src]$ uname -a
Linux localhost.localdomain 3.6.11-4.fc16.x86_64 #1 SMP Tue Jan 8 20:57:42 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

But I removed the -mx32 switch before compiling. btw, why is it there? It looks like a strange switch.

Tests are kinda working, but a run on a different exe gave me this:
ESC[1;33m24992 System call: write (4) Pre: 1ESC[0m
ESC[1;33m24992 System call: write (4) Pre: 0ESC[0m

and the "write" is not catch by tracy.... running a simple base test.

Why that?

**Comment by MerlijnWajer** [comment] 2015-01-01 23:36
Hi,

The -mx32 (x32 mode) switch is used only to generate the file arch/amd64/syscall_x32.h ; as far as I know/recall. It's added by somewhat recent GCC's, maybe yours is too old?

Also - I think the base test should catch the write? What exe did it not work on?

On this topic: I do have an x86_64 machine again, so I could test this later -- although I don't recall getting problems last time I tried it.

**Comment by mariotti** [comment] 2015-01-02 00:08
okey ;) my machine has an old OS:
[mariotti@localhost Linux x86+64bit]$ cat /etc/redhat-release 
Fedora release 16 (Verne)

and I guess and old gcc: 
[mariotti@localhost Linux x86+64bit]$ gcc --version
gcc (GCC) 4.6.3 20120306 (Red Hat 4.6.3-2)

But I think tracy related things are not that fast growing as the web ;)
I would expect basic OS hooks. It compiles and runs, at least few tests.

Indeed, you write too, the uname dependency, should be made a bit better. ;)
I think the main problem is x86_64 and not i386 ... as I compile as an amd64.

The exe I was testing is from: http://www.cgm-online.com/rc-heli-simulator/_download.html
Do not panic, I am not a cracker ;)

But I would not mind to prove a different licence protection.
i.e. technically "tracy" gives the possibility to a "low" technically skilled person to crack or better
hijack some licence protections.

At least for what is running in the user space.

Might this be indeed the problem? I was running in the user space....

**Comment by mariotti** [comment] 2015-01-02 00:28
the -mx32 is given as switch to gcc... i.e. does not generate any file. in principle..

but it is assumed for an x86_64 architecture which given with the amd64 uname .. 

a simple google gave me this:
http://stackoverflow.com/questions/10860367/is-the-mx32-gcc-flag-implemented-correctly

http://stackoverflow.com/questions/24041752/compile-c-program-for-x86-with-gcc-doesnt-use-avx-instruction-set

I am not that expert, but if there is a dependency it should be on the running OS and eventually on
the guest application.

**Comment by MerlijnWajer** [comment] 2015-01-02 09:31
The -mx32 flag on GCC tells GCC to work in 'x32' mode, x32 mode is not amd64 (x86_64) and also not i386/i686 (x86); it's a separate thing that was added but it used by practically no one. Our support for it is also untested. That being said, it should not interfere with your usage of tracy, mostly. Unless your compiler does not have the flag yet -- then I suggest removing the x32 support altogether (I can help with this). We're definitely also supporting older Linux systems.

Perhaps you can run make clean, and then make, and show me the output? (Without modifications to the file)

So what you noticed is that certain system calls are not logged by Tracy. More specifically, using 'base' on the binary you linked. It's possible that their binary is i686 instead of amd64 bit. Tracy should be able to detect this and provide you with the proper 32 bit system call, when you use the right functions. (tracy_set_hook with the proper abi argument)

tracy_set_hook(t, "write", TRACY_ABI_X86, <function pointer>)

Let me know. :)

**Comment by MerlijnWajer** [comment] 2015-01-02 10:04
Alternatively, you can compile tracy in 32 bit mode, if you're only going to work on 32 bit binaries. It may be easier in certain cases.

**Comment by fabmariotti** [comment] 2015-01-05 16:55
Okey, for the moment removing the -mx32 switch seems to work. Random hand made test runs seems to compile and run on simple commands. Like ./fuzz-write ls
Please note that everything goes under amd64 even if this is an intel, i.e. the x86_64 flag is used.
which I think it is okey somehow at present as it should not differ too much...if not at all.
Switching to TRACY_ABI_X86 gets traced the calls indeed. But of course the results are a bit unexpected as, if I get it well, we are on a 64 bit machine using a 32 bit calls. I am sorry I got till now
little time so I cannot give you more specific details. Simply random files are created on tracing write ;)
I will try to reproduce it and come back....

**Comment by fabmariotti** [comment] 2015-01-05 16:57
btw.. all in the user space.. kind of comfortable indeed ;)

**Comment by MerlijnWajer** [comment] 2015-01-06 18:35
amd64 is the generic name for x86_64. They are the same. So intel 64 bit is "amd64". On a 64 bit machine you can execute 32 bit system calls, it's just a bit more difficult to get it right if your tracer is 64 bit.

More details would be appreciated.

**Comment by v1kko** [comment] 2015-05-19 18:14
I think this issue is fixed now. see: https://github.com/MerlijnWajer/tracy/commit/f83ed148f3b20fcddee56dd6ef64720790ac73ea

**Comment by MerlijnWajer** [comment] 2015-05-19 18:28
Yes, it is likely the same issue as the one @v1kko and I ran into today. I'll create a CREDITS file and credit you as well, if you want, @mariotti / @fabmariotti :-)

**Comment by MerlijnWajer** [comment] 2015-05-19 18:29
I'm tired -- I should have mentioned @M1cha . :-)

**Closed** 2015-05-19 18:28 UTC
